services:
  - type: web
    name: nyotatech-suite
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: file
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        sync: false
      - key: DB_URL
        sync: false
